<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Thank you for your registration</title>
    <style>
        body {
            background: #80ffa0;
        }

        h1 {
            color: black;
            text-shadow: aqua;
        }

        h2 {
            color: red;
            text-shadow: aqua;
        }
    </style>
</head>
<body>
<h1>Registration link:</h1>
<img src="https://memepedia.ru/wp-content/uploads/2018/09/bongo-cat-768x432.jpg" alt="BongoNet logo">
<h2><a href="${server_url}/confirm/${confirm_code}">Follow the link</a></h2>
</body>
</html>
