<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Thank you for your registration</title>
    <style>
        h2 {
            color: cadetblue;
        }
    </style>
</head>
<body>
<h2>Please, <a href="${server_url}/confirm/${confirm_code}">follow the link</a> to verify your account</h2>
<img src="https://res.cloudinary.com/teepublic/image/private/s--U9hrNyng--/t_Resized%20Artwork/c_fit,g_north_west,h_1054,w_1054/co_ffffff,e_outline:53/co_ffffff,e_outline:inner_fill:53/co_bbbbbb,e_outline:3:1000/c_mpad,g_center,h_1260,w_1260/b_rgb:eeeeee/c_limit,f_jpg,h_630,q_90,w_630/v1537322064/production/designs/3177096_0.jpg"
     alt="BongoNet logo">
</body>
</html>
