<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/main.css">
    <title>Profile</title>
</head>
<body>
<div class="container">
    <p>PROFILE</p>
    <p>Hello, ${user.username}</p>
    <p>This is your profile page. Well, it's quite отвратительная немножечко очень сильно, но команда это поправит.</p>
    <p>Когда-нибудь...</p>
</div>
</body>
</html>
