<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://netdna.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="styles/confirm_page_style.css">
    <link rel="icon" href="/images/favicon.ico"/>
    <title>Success!</title>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col">
            <div class="card border-primary">
                <div class="card-header text-center">
                    <div class="card-title">
                        <b>Thank you for registering with us!</b>
                    </div>
                </div>
                <div class="card-img-top text-center">
                    <img src="https://res.cloudinary.com/teepublic/image/private/s--U9hrNyng--/t_Resized%20Artwork/c_fit,g_north_west,h_1054,w_1054/co_ffffff,e_outline:53/co_ffffff,e_outline:inner_fill:53/co_bbbbbb,e_outline:3:1000/c_mpad,g_center,h_1260,w_1260/b_rgb:eeeeee/c_limit,f_jpg,h_630,q_90,w_630/v1537322064/production/designs/3177096_0.jpg"
                         alt="logo">
                </div>
                <div class="card-body text-center">
                    <p>
                        We are excited to have you join us in BongoNet community.
                    </p>
                    <p>
                        Please follow the link below to sign in with your new account
                    </p>
                    <a href="/auth" class="btn btn-outline-primary">Sign in</a>
                </div>
                <div class="card-footer text-center text-secondary">
                    &copy; 2021 BongoNetTeam
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>
